-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 10:23:59 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema globantWorkshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema globantWorkshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `globantWorkshop` DEFAULT CHARACTER SET utf8 ;
USE `globantWorkshop` ;

-- -----------------------------------------------------
-- Table `globantWorkshop`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globantWorkshop`.`books` (
  `idbooks` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Author` VARCHAR(100) NULL DEFAULT NULL,
  `ISBN` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idbooks`),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `globantWorkshop`.`copies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globantWorkshop`.`copies` (
  `idcopies` INT(11) NOT NULL AUTO_INCREMENT,
  `bookCondition` VARCHAR(45) NULL DEFAULT NULL,
  `taken` INT(1) NULL DEFAULT NULL,
  `books_idbooks` INT(11) NOT NULL,
  PRIMARY KEY (`idcopies`),
  INDEX `fk_copies_books1_idx` (`books_idbooks` ASC),
  CONSTRAINT `fk_copies_books1`
    FOREIGN KEY (`books_idbooks`)
    REFERENCES `globantWorkshop`.`books` (`idbooks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `globantWorkshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globantWorkshop`.`users` (
  `idusers` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `lastname` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `DNI` INT(8) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `globantWorkshop`.`rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globantWorkshop`.`rentals` (
  `users_idusers` INT(11) NOT NULL AUTO_INCREMENT,
  `rentalDate` DATETIME NULL DEFAULT NULL,
  `returnDate` DATETIME NULL DEFAULT NULL,
  `posible` INT(1) NULL DEFAULT NULL,
  `copies_idcopies` INT(11) NOT NULL,
  `id_rentals` INT(11) NOT NULL,
  PRIMARY KEY (`users_idusers`, `copies_idcopies`),
  INDEX `fk_users_has_books_users_idx` (`users_idusers` ASC),
  INDEX `fk_rentals_copies1_idx` (`copies_idcopies` ASC),
  CONSTRAINT `fk_rentals_copies1`
    FOREIGN KEY (`copies_idcopies`)
    REFERENCES `globantWorkshop`.`copies` (`idcopies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `globantWorkshop`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
